version: '3.8'

services:
  ai-dashboard:
    build: .
    ports:
      - "8881:3000"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://dashboard:${DB_PASSWORD:-ai_spend_secure_password_2024}@postgres:5432/ai_spend
      - OPENAI_API_KEY=${OPENAI_API_KEY:-placeholder-openai-key}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-placeholder-anthropic-key}
      - PORT=3000
    volumes:
      - ./ssl:/app/ssl:ro
    networks:
      - ai-dashboard-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      - POSTGRES_DB=ai_spend
      - POSTGRES_USER=dashboard
      - POSTGRES_PASSWORD=${DB_PASSWORD:-ai_spend_secure_password_2024}
    networks:
      - ai-dashboard-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dashboard -d ai_spend"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  postgres_data:
    driver: local

networks:
  ai-dashboard-network:
    driver: bridge