version: '3.8'

services:
  ai-dashboard:
    image: ai-spend-dashboard:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9443:3000"
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
      INFISICAL_CLIENT_ID: ${INFISICAL_CLIENT_ID}
      INFISICAL_CLIENT_SECRET: ${INFISICAL_CLIENT_SECRET}
      INFISICAL_PROJECT_ID: ${INFISICAL_PROJECT_ID}
      INFISICAL_ENVIRONMENT: production
      DATABASE_URL: postgresql://dashboard:${DB_PASSWORD}@postgres:5432/ai_spend
    volumes:
      - ssl_certs:/app/ssl:ro
    networks:
      - ai-dashboard-network

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ai_spend
      POSTGRES_USER: dashboard
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - ai-dashboard-network

volumes:
  postgres_data:
  ssl_certs:

networks:
  ai-dashboard-network: